name: 'Tauri Build Artifacts'

on:
  push

jobs:  
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./wondrium_tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `wondrium-v${process.env.PACKAGE_VERSION}`,
              name: `Wondrium v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install this app.',
              draft: true,
              prerelease: false
            })

            return data.id

  build-tauri:
    needs: [create-release]
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: install tailwind-cli and build yew app (windows only)
      if: matrix.platform == 'windows-latest'
      run: |
        Invoke-WebRequest -OutFile tailwindcss.exe https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-windows-x64.exe
        mv tailwindcss.exe wondrium_yew/tailwindcss.exe
        cd wondrium_yew && trunk build
    - name: install tailwind-cli and build yew app (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
       curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
       chmod +x tailwindcss-linux-x64
       mv tailwindcss-linux-x64 wondrium_yew/tailwindcss
       cd wondrium_yew && trunk build
    - name: install tailwind-cli and build yew app (macos only)
      if: matrix.platform == 'macos-latest'
      run: |
       curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-x64
       chmod +x tailwindcss-macos-x64
       mv tailwindcss-macos-x64 wondrium_yew/tailwindcss
       cd wondrium_yew
       ls
       trunk -v build
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-latest
    needs: [ create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
